### PR TITLE
Add report naming functionality

### LINKED ISSUE #41: More flexible report naming
Currently all reports generated by the builder have the same name and differ only by their file extension (e.g. `foo.html`, `foo.json`, `foo.retry`). It would be useful to be able to specify different, more meaningful names to the different report types (e.g. `report.html`, `raw.json`, `failures.retry`).

### PR DESCRIPTION
**Pull request by enkessler**
This fixes #41.

### CODE REVIEW

**Comment by enkessler** [comment]
@rajatthareja, @tk8817  What do you think?

**Comment by tk8817** [comment]
I am good with these changes @enkessler / @rajatthareja

**Comment by tk8817** [comment]
do you mind squashing and then I will merge.

**Comment by enkessler** [comment]
I'm pretty sure that squashing is one of the options when merging via the little drop down menu..

**Pull request merged**
